### ISSUE TITLE
Storybookに関するディレクトリ構成について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#12]
今のディレクトリ構成でいくと、Storybookファイルが増えていく場合かなりカオスなディレクトリ構成になりそうです
（現状のコンポーネントファイルと並列に設置されているので）

軽く代替案を挙げると以下の２つかなぁと

1. `src/stories`にまとめる
  - `src/components`配下のディレクトリ構造をそのまま`src/stories`に移すようにして整理整頓するパターンです

2. 各コンポーネントに対してディレクトリを１つ挟む
  - `src/components/button/PrimaryButton/index.tsx`に今の`PrimaryButton.tsx`を移すイメージです
  - Storybookを定義する場合は`/PrimaryButton/index.stories.tsx`を設置するイメージ
  - おまけですが、このようなディレクトリ構成にすると、テストファイルも`/PrimaryButton/index.test.tsx`のように設置することができます

一旦ディレクトリ構成系の記事を読み漁ってみるのも良いかと思います〜
１つだけ良記事置いときます
https://note.com/tabelog_frontend/n/n07b4077f5cf3

**Comment by mizushima1226** [comment]
ついでに`src/components`の直下に設置しているコンポーネントが増えてきたのでディレクトリ切って整理整頓しておくとよさそうです〜💡

**Comment by yiinuma** [comment]
案２の方法を採用しました
またcomponents直下はpagesとuiPatrsに分けて整理しなおしました

**Comment by mizushima1226** [comment]
修正内容確認できました〜
ディレクトリ構成は正解がないので常にベストを探りつつ、その時納得できる考えを持って進んでいく、くらいの認識で良いと思います👍

現状でいくと、`src/pages`があるのに対して`src/components/page`のディレクトリを切っているところが少し違和感でした

↑も含め、今後ディレクトリ構成について調べたり考えたりしてみると良いと思います

このissue自体はcloseしてOKです〜👍

**Comment by yiinuma** [comment]
`components/pages`を`component/specificPage`　にしました
