### ISSUE TITLE
メモ画面の表示が崩れている？

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#2]
添付したキャプチャは一番上にスクロールしている状態ですが、入力フォームが見えなくなっているように見えます🤔
検証ツールで見てみると、メモの一覧も一部見えなくなっているようです

<img width="1512" alt="スクリーンショット 2022-05-05 9 53 11" src="https://user-images.githubusercontent.com/47247884/166849552-4405e000-fe78-4b13-9bac-fe071a180cea.png">

**Comment by yiinuma** [comment]
Layoutの高さ指定を修正しました
h-screen→min-h-screen
