### ISSUE TITLE
CSRでサーバーエラー

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#3]
http://localhost:3000/csr　のurlでサーバーエラーを発見しました👀
一旦お手元の環境で再現するか確認お願いします🙇‍♂️

```
Server Error
Error: Image is missing required "src" property. Make sure you pass "src" in props to the `next/image` component. Received: {"width":480,"height":320}
```

**Comment by mizushima1226** [comment]
memo
プロダクションビルドでアプリ起動すると再現しない

**Comment by yiinuma** [comment]
src={img} のimgが取得できない時は表示しないようにしました
`  {img && <Image src={img} width={480} height={320} alt='dogs' objectFit='cover' />}`
