### ISSUE TITLE
modalStateについて

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#4]
`modalState`をhookに隠蔽していますが、
`modalState`を`export`してしまうと外部から参照されてしまう可能性がありますね👀

exportしないようにすると、外部から参照されないことが保証され、他者にその意図が伝わりやすくなります
exportしてしまうと、外部参照して良い、の意図に汲み取ってしまうかもです〜

**Comment by yiinuma** [comment]
`modalState` と`editIndexState`の`export`を削除しました
