### ISSUE TITLE
ログイン時の処理について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#5]
loginのエンドポイントにpost後の処理ですが、onSuccessやonErrorでハンドリングした方が良さそうですね👀
mutationFnでのハンドリングと混ざりそうな印象です🤔
何か事情があっての実装であれば共有いただけると幸いです〜

https://github.com/yiinuma/CSR_SSG_SSR_ISR_inNextjs/blob/cba26bbb27a9295cf9d53de5d83c8c8ca79c52df/src/hooks/useMutateAuth.ts#L34-L51

**Comment by yiinuma** [comment]
特に意図はないので、onSuccessに移動しました
