### ISSUE TITLE
動的ルーティングについて

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/CSR_SSG_SSR_ISR_inNextjs#9]
ブログ一覧・ブログ詳細画面があるかと思います
現状、以下のようにルーティングされています

- `/pages/blob-page` : ブログ一覧
- `/pages/posts/[id]`：ブログ詳細

一覧・詳細画面はよくある画面設計ですが、一覧は以下のようにするのが一般的です
- `/pages/posts/index.tsx`
  `http://localhost:3000/posts`のURLで`index.tsx`のブログ一覧画面にルーティングされます

**Comment by yiinuma** [comment]
/page/blog/index
/page/blog/[id]
の構成に変更しました
